### PR TITLE
Added support for OWA/365 Calendar Notifications

### PR DESCRIPTION
**Pull request by jarrettroth**
Lots of changes:
- Cleaned up a bunch of code
- Renamed most functions to help with understanding the code (should help with future contributions)
- Did not add any additional png's for calendar notifications
- Removed the red favicon message count, since the count already is added to document title.
- Broke most functions over 10 lines to smaller functions.
- Both tests pass
- Tested on both outlook 365 and owa.

### CODE REVIEW

**Comment by rockfield** [comment]
Thank you a lot! I'll integrate it soon.
Favicon is needed in case with a lot of tabs and one's width the same as favicon.
What do you think of this?

**Comment by jarrettroth** [comment]
I was thinking, the reason for the favicon was exactly for multiple tabs.  How about we clean it up (taller, slightly wider, rounded corners, gray background and white font)?

**Comment by rockfield** [comment]
Yeah :+1:

**Comment by jarrettroth** [comment]
@rockfield I added a revamped look to the favicon and a git ignore file so that you can create a profile-dir directory to point firefox to so that you have some autocomplete during debugging. 
image

**Comment by rockfield** [comment]
Here some changes has been released to add support 2010 version.

I need to merge a lot of changes and clarify some moments.
Please, help me.

I guess, this code has original parsing method ( .match(/\d/gi).join("") ):
```javascript
function getCountFromHTML(container){
    return parseInt(container.innerHTML.match(/\d/gi).join(""), 10);
}
```
Later this method had been changed to the following to avoid Junk & Drafts folders checking
```javascript
.match(/\d{1,} unread/gi);
```
before the one has been changed to bigger function to fix 2010 version support:
```javascript
function countIt(unreadContainer, legacySupport) {
	var count = 0;
	for(var u_node = unreadContainer.length-1; u_node>=0; u_node--) {
		var amountHtml = unreadContainer[u_node].innerHTML; 
		var amountArr = amountHtml.match(/\d{1,} unread/gi);
		var amount = amountHtml.match(/\d/gi).join('');
		if ( Array.isArray(amountArr) ) {
			count += parseInt(amountArr[0], 10);
		} else if ( legacySupport ) {
			count += parseInt(amount, 10);
		}
	}
	return count;
}
```

The getCountFromHTML function is just renamed original countIt function, isn't it?
I think I can use it like this:

**Comment by rockfield** [comment]
@phalox could you check the performance of new version?
commit f56a3094f0d533f1e1a99be9e091a9334f83b192

**Comment by rockfield** [comment]
@phalox I mean with 2010 version if you have opportunity.

**Comment by phalox** [comment]
@rockfield Sorry I'm quite busy at the moment.

I noticed that there are 2 different versions of the OWA plugin in the app store. Which one is which?

**Comment by rockfield** [comment]
@phalox oh I have the same problem.
the one: https://addons.mozilla.org/en-US/firefox/addon/owa_firefox_addon/?src=search

**Comment by rockfield** [comment]
@phalox oh I have the same problem.
You can generate the one or grab from here: http://gaers.ru/philipp1@jabber.ru/owa_notifications.xpi

**Comment by phalox** [comment]
thanks, this file helps me a lot :-) if I have to figure out how to compile it all again I couldn't do it now.
untitled

The icon and notification work and count correctly. The count in the title seems to be wrong though.

**Comment by rockfield** [comment]
can you try the one?
http://gaers.ru/philipp1@jabber.ru/owa_notifications_635.xpi

**Comment by phalox** [comment]
1_email2015-03-28_214713
2_email2015-03-28_214713

Seems to be working, though I don't fully understand what the 0/0 means...

**Comment by phalox** [comment]
One more thing. When outlook logs out automatically after a while, you still get to see the count icon.
with the previous version it went back to the old icon...
logout_2015-03-29_103622

**Pull request closed without merging**
